// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokeSaveRomManager.Data;

#nullable disable

namespace PokeSaveRomManager.Data.Migrations
{
    [DbContext(typeof(PokemonDbContext))]
    [Migration("20250422134013_TypeGame")]
    partial class TypeGame
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Box", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Boxes");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.BoxSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BoxId")
                        .HasColumnType("integer");

                    b.Property<int>("PokemonInstanceId")
                        .HasColumnType("integer");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoxId");

                    b.HasIndex("PokemonInstanceId");

                    b.ToTable("BoxSlots");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FormOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsGigantamax")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMega")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRegional")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<int>("Type1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Type2Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("Type1Id");

                    b.HasIndex("Type2Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Generation")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Official")
                        .HasColumnType("boolean");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Move", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Accuracy")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Effect")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PP")
                        .HasColumnType("integer");

                    b.Property<int?>("Power")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TypeId");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.MoveGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("MoveGameId")
                        .HasColumnType("integer");

                    b.Property<int>("MoveId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("MoveId");

                    b.ToTable("MoveGame");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.MoveLearning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEggMove")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTutor")
                        .HasColumnType("boolean");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MethodId")
                        .HasColumnType("integer");

                    b.Property<int>("MoveGameId")
                        .HasColumnType("integer");

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<string>("TMNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MethodId");

                    b.HasIndex("MoveGameId");

                    b.HasIndex("PokemonId");

                    b.ToTable("MoveLearning");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.MoveLearningMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MoveLearningMethods");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Nature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DecreasedStatId")
                        .HasColumnType("integer");

                    b.Property<int?>("IncreasedStatId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StatId")
                        .HasColumnType("integer");

                    b.Property<int?>("StatId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DecreasedStatId");

                    b.HasIndex("IncreasedStatId");

                    b.HasIndex("StatId");

                    b.HasIndex("StatId1");

                    b.ToTable("Natures");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Attack")
                        .HasColumnType("integer");

                    b.Property<int>("Defense")
                        .HasColumnType("integer");

                    b.Property<int>("DexNumber")
                        .HasColumnType("integer");

                    b.Property<string>("FormName")
                        .HasColumnType("text");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("HP")
                        .HasColumnType("integer");

                    b.Property<bool>("IsGigantamax")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMega")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRegionalForm")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpAttack")
                        .HasColumnType("integer");

                    b.Property<int>("SpDefense")
                        .HasColumnType("integer");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<int>("Type1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Type2Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("Type1Id");

                    b.HasIndex("Type2Id");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.PokemonAbility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AbilityId")
                        .HasColumnType("integer");

                    b.Property<int>("AbilitySlot")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("PokemonId");

                    b.ToTable("PokemonAbilities");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.PokemonInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AbilityId")
                        .HasColumnType("integer");

                    b.Property<int?>("EVAttack")
                        .HasColumnType("integer");

                    b.Property<int?>("EVDefense")
                        .HasColumnType("integer");

                    b.Property<int?>("EVHP")
                        .HasColumnType("integer");

                    b.Property<int?>("EVSpAttack")
                        .HasColumnType("integer");

                    b.Property<int?>("EVSpDefense")
                        .HasColumnType("integer");

                    b.Property<int?>("EVSpeed")
                        .HasColumnType("integer");

                    b.Property<int?>("FormId")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("HeldItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("IVAttack")
                        .HasColumnType("integer");

                    b.Property<int?>("IVDefense")
                        .HasColumnType("integer");

                    b.Property<int?>("IVHP")
                        .HasColumnType("integer");

                    b.Property<int?>("IVSpAttack")
                        .HasColumnType("integer");

                    b.Property<int?>("IVSpDefense")
                        .HasColumnType("integer");

                    b.Property<int?>("IVSpeed")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int?>("MetLevel")
                        .HasColumnType("integer");

                    b.Property<string>("MetLocation")
                        .HasColumnType("text");

                    b.Property<int?>("Move1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Move2Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Move3Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Move4Id")
                        .HasColumnType("integer");

                    b.Property<int?>("MoveId")
                        .HasColumnType("integer");

                    b.Property<int?>("MoveId1")
                        .HasColumnType("integer");

                    b.Property<int?>("MoveId2")
                        .HasColumnType("integer");

                    b.Property<int?>("MoveId3")
                        .HasColumnType("integer");

                    b.Property<int?>("NatureId")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<string>("OriginalTrainerId")
                        .HasColumnType("text");

                    b.Property<string>("OriginalTrainerName")
                        .HasColumnType("text");

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<string>("Ribbons")
                        .HasColumnType("text");

                    b.Property<bool>("Shiny")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("FormId");

                    b.HasIndex("GameId");

                    b.HasIndex("HeldItemId");

                    b.HasIndex("Move1Id");

                    b.HasIndex("Move2Id");

                    b.HasIndex("Move3Id");

                    b.HasIndex("Move4Id");

                    b.HasIndex("MoveId");

                    b.HasIndex("MoveId1");

                    b.HasIndex("MoveId2");

                    b.HasIndex("MoveId3");

                    b.HasIndex("NatureId");

                    b.HasIndex("PokemonId");

                    b.HasIndex("UserId");

                    b.ToTable("PokemonInstances");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Stat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PokemonInstanceId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PokemonInstanceId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.TypeGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TypeId");

                    b.ToTable("TypeGame");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Box", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Entities.Game", "Game")
                        .WithMany("Boxes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Entities.User", "User")
                        .WithMany("Boxes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.BoxSlot", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Entities.Box", "Box")
                        .WithMany("Slots")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Entities.PokemonInstance", "PokemonInstance")
                        .WithMany("BoxSlots")
                        .HasForeignKey("PokemonInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");

                    b.Navigation("PokemonInstance");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Form", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Entities.Pokemon", "Pokemon")
                        .WithMany("Forms")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Entities.Type", "Type1")
                        .WithMany()
                        .HasForeignKey("Type1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Entities.Type", "Type2")
                        .WithMany()
                        .HasForeignKey("Type2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pokemon");

                    b.Navigation("Type1");

                    b.Navigation("Type2");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Move", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Entities.Category", "Category")
                        .WithMany("Moves")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Entities.Type", "Type")
                        .WithMany("Moves")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.MoveGame", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Entities.Game", "Game")
                        .WithMany("MoveGame")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Entities.Move", "Move")
                        .WithMany("MoveGame")
                        .HasForeignKey("MoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Move");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.MoveLearning", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Entities.MoveLearningMethod", "Method")
                        .WithMany("MoveLearning")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Entities.MoveGame", "MoveGame")
                        .WithMany()
                        .HasForeignKey("MoveGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Entities.Pokemon", "Pokemon")
                        .WithMany("MoveLearning")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Method");

                    b.Navigation("MoveGame");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Nature", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Entities.Stat", "DecreasedStat")
                        .WithMany()
                        .HasForeignKey("DecreasedStatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeSaveRomManager.Data.Entities.Stat", "IncreasedStat")
                        .WithMany()
                        .HasForeignKey("IncreasedStatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeSaveRomManager.Data.Entities.Stat", null)
                        .WithMany("DecreasedNatures")
                        .HasForeignKey("StatId");

                    b.HasOne("PokeSaveRomManager.Data.Entities.Stat", null)
                        .WithMany("IncreasedNatures")
                        .HasForeignKey("StatId1");

                    b.Navigation("DecreasedStat");

                    b.Navigation("IncreasedStat");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Pokemon", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Entities.Game", "Game")
                        .WithMany("Pokemon")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Entities.Type", "Type1")
                        .WithMany()
                        .HasForeignKey("Type1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Entities.Type", "Type2")
                        .WithMany()
                        .HasForeignKey("Type2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Game");

                    b.Navigation("Type1");

                    b.Navigation("Type2");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.PokemonAbility", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Entities.Ability", "Ability")
                        .WithMany("PokemonAbilities")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Entities.Pokemon", "Pokemon")
                        .WithMany("Abilities")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.PokemonInstance", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Entities.Ability", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId");

                    b.HasOne("PokeSaveRomManager.Data.Entities.Form", "Form")
                        .WithMany("PokemonInstances")
                        .HasForeignKey("FormId");

                    b.HasOne("PokeSaveRomManager.Data.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Entities.Item", "HeldItem")
                        .WithMany("PokemonInstances")
                        .HasForeignKey("HeldItemId");

                    b.HasOne("PokeSaveRomManager.Data.Entities.Move", "Move1")
                        .WithMany()
                        .HasForeignKey("Move1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeSaveRomManager.Data.Entities.Move", "Move2")
                        .WithMany()
                        .HasForeignKey("Move2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeSaveRomManager.Data.Entities.Move", "Move3")
                        .WithMany()
                        .HasForeignKey("Move3Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeSaveRomManager.Data.Entities.Move", "Move4")
                        .WithMany()
                        .HasForeignKey("Move4Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeSaveRomManager.Data.Entities.Move", null)
                        .WithMany("PokemonInstancesWithMove1")
                        .HasForeignKey("MoveId");

                    b.HasOne("PokeSaveRomManager.Data.Entities.Move", null)
                        .WithMany("PokemonInstancesWithMove2")
                        .HasForeignKey("MoveId1");

                    b.HasOne("PokeSaveRomManager.Data.Entities.Move", null)
                        .WithMany("PokemonInstancesWithMove3")
                        .HasForeignKey("MoveId2");

                    b.HasOne("PokeSaveRomManager.Data.Entities.Move", null)
                        .WithMany("PokemonInstancesWithMove4")
                        .HasForeignKey("MoveId3");

                    b.HasOne("PokeSaveRomManager.Data.Entities.Nature", "Nature")
                        .WithMany("PokemonInstances")
                        .HasForeignKey("NatureId");

                    b.HasOne("PokeSaveRomManager.Data.Entities.Pokemon", "Pokemon")
                        .WithMany("Instances")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Entities.User", "User")
                        .WithMany("PokemonInstances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Form");

                    b.Navigation("Game");

                    b.Navigation("HeldItem");

                    b.Navigation("Move1");

                    b.Navigation("Move2");

                    b.Navigation("Move3");

                    b.Navigation("Move4");

                    b.Navigation("Nature");

                    b.Navigation("Pokemon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Team", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Entities.Game", "Game")
                        .WithMany("Teams")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Entities.User", "User")
                        .WithMany("Teams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.TeamMember", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Entities.PokemonInstance", "PokemonInstance")
                        .WithMany("TeamMembers")
                        .HasForeignKey("PokemonInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PokemonInstance");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.TypeGame", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Entities.Game", "Game")
                        .WithMany("TypeGame")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Entities.Type", "Type")
                        .WithMany("TypeGame")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Ability", b =>
                {
                    b.Navigation("PokemonAbilities");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Box", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Category", b =>
                {
                    b.Navigation("Moves");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Form", b =>
                {
                    b.Navigation("PokemonInstances");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Game", b =>
                {
                    b.Navigation("Boxes");

                    b.Navigation("MoveGame");

                    b.Navigation("Pokemon");

                    b.Navigation("Teams");

                    b.Navigation("TypeGame");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Item", b =>
                {
                    b.Navigation("PokemonInstances");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Move", b =>
                {
                    b.Navigation("MoveGame");

                    b.Navigation("PokemonInstancesWithMove1");

                    b.Navigation("PokemonInstancesWithMove2");

                    b.Navigation("PokemonInstancesWithMove3");

                    b.Navigation("PokemonInstancesWithMove4");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.MoveLearningMethod", b =>
                {
                    b.Navigation("MoveLearning");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Nature", b =>
                {
                    b.Navigation("PokemonInstances");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Pokemon", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Forms");

                    b.Navigation("Instances");

                    b.Navigation("MoveLearning");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.PokemonInstance", b =>
                {
                    b.Navigation("BoxSlots");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Stat", b =>
                {
                    b.Navigation("DecreasedNatures");

                    b.Navigation("IncreasedNatures");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.Type", b =>
                {
                    b.Navigation("Moves");

                    b.Navigation("TypeGame");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Entities.User", b =>
                {
                    b.Navigation("Boxes");

                    b.Navigation("PokemonInstances");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
