// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokeSaveRomManager.Data;

#nullable disable

namespace PokeSaveRomManager.Data.Migrations
{
    [DbContext(typeof(PokemonDbContext))]
    [Migration("20250503173337_ChangedPokemonFormRelations")]
    partial class ChangedPokemonFormRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NameId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NameId");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.AbilityName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AbilityNames");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Generation")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Official")
                        .HasColumnType("boolean");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.GameAbility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AbilityId")
                        .HasColumnType("integer");

                    b.Property<int>("AbilityInGameId")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("GameId");

                    b.ToTable("GameAbilities");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.GameMove", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("MoveId")
                        .HasColumnType("integer");

                    b.Property<int>("MoveInGameId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("MoveId");

                    b.ToTable("GameMoves");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.GameType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeInGameId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TypeId");

                    b.ToTable("GameTypes");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Move", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Accuracy")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Effect")
                        .HasColumnType("text");

                    b.Property<int>("NameId")
                        .HasColumnType("integer");

                    b.Property<int?>("PP")
                        .HasColumnType("integer");

                    b.Property<int?>("Power")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NameId");

                    b.HasIndex("TypeId");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.MoveLearningMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MoveLearningMethods");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.MoveName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MoveNames");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Nature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DecreasedStatId")
                        .HasColumnType("integer");

                    b.Property<int?>("IncreasedStatId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StatId")
                        .HasColumnType("integer");

                    b.Property<int?>("StatId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DecreasedStatId");

                    b.HasIndex("IncreasedStatId");

                    b.HasIndex("StatId");

                    b.HasIndex("StatId1");

                    b.ToTable("Natures");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DexNumber")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.PokemonAbility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AbilityId")
                        .HasColumnType("integer");

                    b.Property<int>("AbilitySlot")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("PokemonId");

                    b.ToTable("PokemonAbilities");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.PokemonForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Attack")
                        .HasColumnType("integer");

                    b.Property<int>("Defense")
                        .HasColumnType("integer");

                    b.Property<int>("HP")
                        .HasColumnType("integer");

                    b.Property<int?>("InternalId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGigantamax")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMega")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRegional")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<int?>("SpAttack")
                        .HasColumnType("integer");

                    b.Property<int?>("SpDefense")
                        .HasColumnType("integer");

                    b.Property<int?>("Special")
                        .HasColumnType("integer");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<int>("Type1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Type2Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("Type1Id");

                    b.HasIndex("Type2Id");

                    b.ToTable("PokemonForms");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.PokemonInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AbilityId")
                        .HasColumnType("integer");

                    b.Property<int?>("EVAttack")
                        .HasColumnType("integer");

                    b.Property<int?>("EVDefense")
                        .HasColumnType("integer");

                    b.Property<int?>("EVHP")
                        .HasColumnType("integer");

                    b.Property<int?>("EVSpAttack")
                        .HasColumnType("integer");

                    b.Property<int?>("EVSpDefense")
                        .HasColumnType("integer");

                    b.Property<int?>("EVSpecial")
                        .HasColumnType("integer");

                    b.Property<int?>("EVSpeed")
                        .HasColumnType("integer");

                    b.Property<int>("FormId")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("HeldItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("IVAttack")
                        .HasColumnType("integer");

                    b.Property<int?>("IVDefense")
                        .HasColumnType("integer");

                    b.Property<int?>("IVHP")
                        .HasColumnType("integer");

                    b.Property<int?>("IVSpAttack")
                        .HasColumnType("integer");

                    b.Property<int?>("IVSpDefense")
                        .HasColumnType("integer");

                    b.Property<int?>("IVSpecial")
                        .HasColumnType("integer");

                    b.Property<int?>("IVSpeed")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int?>("Move1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Move2Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Move3Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Move4Id")
                        .HasColumnType("integer");

                    b.Property<int?>("MoveId")
                        .HasColumnType("integer");

                    b.Property<int?>("MoveId1")
                        .HasColumnType("integer");

                    b.Property<int?>("MoveId2")
                        .HasColumnType("integer");

                    b.Property<int?>("MoveId3")
                        .HasColumnType("integer");

                    b.Property<int?>("NatureId")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<int>("SaveId")
                        .HasColumnType("integer");

                    b.Property<bool>("Shiny")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("FormId");

                    b.HasIndex("HeldItemId");

                    b.HasIndex("Move1Id");

                    b.HasIndex("Move2Id");

                    b.HasIndex("Move3Id");

                    b.HasIndex("Move4Id");

                    b.HasIndex("MoveId");

                    b.HasIndex("MoveId1");

                    b.HasIndex("MoveId2");

                    b.HasIndex("MoveId3");

                    b.HasIndex("NatureId");

                    b.HasIndex("PokemonId");

                    b.HasIndex("SaveId");

                    b.ToTable("PokemonInstances");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.PokemonMove", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameInMoveId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEggMove")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTutor")
                        .HasColumnType("boolean");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MethodId")
                        .HasColumnType("integer");

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<string>("TMNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameInMoveId");

                    b.HasIndex("MethodId");

                    b.HasIndex("PokemonId");

                    b.ToTable("PokemonMove");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Save", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("Saves");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.SaveBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("SaveId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SaveId");

                    b.ToTable("SaveBoxes");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.SaveBoxSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BoxId")
                        .HasColumnType("integer");

                    b.Property<int>("PokemonInstanceId")
                        .HasColumnType("integer");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoxId");

                    b.HasIndex("PokemonInstanceId");

                    b.ToTable("SaveBoxSlots");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.SaveTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SaveId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SaveId");

                    b.ToTable("SaveTeams");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.SaveTeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PokemonInstanceId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PokemonInstanceId");

                    b.HasIndex("TeamId");

                    b.ToTable("SaveTeamMembers");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Stat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Auth0Id")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Ability", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Domain.AbilityName", "Name")
                        .WithMany("Abilities")
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Name");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.GameAbility", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Domain.Ability", "Ability")
                        .WithMany("GameAbilities")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Domain.Game", "Game")
                        .WithMany("Abilities")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.GameMove", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Domain.Game", "Game")
                        .WithMany("Moves")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Domain.Move", "Move")
                        .WithMany("GameMoves")
                        .HasForeignKey("MoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Move");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.GameType", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Domain.Game", "Game")
                        .WithMany("Types")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Domain.Type", "Type")
                        .WithMany("GameTypes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Move", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Domain.Category", "Category")
                        .WithMany("Moves")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Domain.MoveName", "Name")
                        .WithMany("Moves")
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Domain.Type", "Type")
                        .WithMany("Moves")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Name");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Nature", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Domain.Stat", "DecreasedStat")
                        .WithMany()
                        .HasForeignKey("DecreasedStatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeSaveRomManager.Data.Domain.Stat", "IncreasedStat")
                        .WithMany()
                        .HasForeignKey("IncreasedStatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeSaveRomManager.Data.Domain.Stat", null)
                        .WithMany("DecreasedNatures")
                        .HasForeignKey("StatId");

                    b.HasOne("PokeSaveRomManager.Data.Domain.Stat", null)
                        .WithMany("IncreasedNatures")
                        .HasForeignKey("StatId1");

                    b.Navigation("DecreasedStat");

                    b.Navigation("IncreasedStat");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Pokemon", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Domain.Game", "Game")
                        .WithMany("Pokemon")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.PokemonAbility", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Domain.Ability", "Ability")
                        .WithMany("PokemonAbilities")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Domain.Pokemon", "Pokemon")
                        .WithMany("Abilities")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.PokemonForm", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Domain.Pokemon", "Pokemon")
                        .WithMany("Forms")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Domain.Type", "Type1")
                        .WithMany()
                        .HasForeignKey("Type1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Domain.Type", "Type2")
                        .WithMany()
                        .HasForeignKey("Type2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pokemon");

                    b.Navigation("Type1");

                    b.Navigation("Type2");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.PokemonInstance", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Domain.Ability", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId");

                    b.HasOne("PokeSaveRomManager.Data.Domain.PokemonForm", "Form")
                        .WithMany("PokemonInstances")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Domain.Item", "HeldItem")
                        .WithMany("PokemonInstances")
                        .HasForeignKey("HeldItemId");

                    b.HasOne("PokeSaveRomManager.Data.Domain.Move", "Move1")
                        .WithMany()
                        .HasForeignKey("Move1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeSaveRomManager.Data.Domain.Move", "Move2")
                        .WithMany()
                        .HasForeignKey("Move2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeSaveRomManager.Data.Domain.Move", "Move3")
                        .WithMany()
                        .HasForeignKey("Move3Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeSaveRomManager.Data.Domain.Move", "Move4")
                        .WithMany()
                        .HasForeignKey("Move4Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeSaveRomManager.Data.Domain.Move", null)
                        .WithMany("PokemonInstancesWithMove1")
                        .HasForeignKey("MoveId");

                    b.HasOne("PokeSaveRomManager.Data.Domain.Move", null)
                        .WithMany("PokemonInstancesWithMove2")
                        .HasForeignKey("MoveId1");

                    b.HasOne("PokeSaveRomManager.Data.Domain.Move", null)
                        .WithMany("PokemonInstancesWithMove3")
                        .HasForeignKey("MoveId2");

                    b.HasOne("PokeSaveRomManager.Data.Domain.Move", null)
                        .WithMany("PokemonInstancesWithMove4")
                        .HasForeignKey("MoveId3");

                    b.HasOne("PokeSaveRomManager.Data.Domain.Nature", "Nature")
                        .WithMany("PokemonInstances")
                        .HasForeignKey("NatureId");

                    b.HasOne("PokeSaveRomManager.Data.Domain.Pokemon", "Pokemon")
                        .WithMany("Instances")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Domain.Save", "Save")
                        .WithMany("PokemonInstances")
                        .HasForeignKey("SaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Form");

                    b.Navigation("HeldItem");

                    b.Navigation("Move1");

                    b.Navigation("Move2");

                    b.Navigation("Move3");

                    b.Navigation("Move4");

                    b.Navigation("Nature");

                    b.Navigation("Pokemon");

                    b.Navigation("Save");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.PokemonMove", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Domain.GameMove", "GameMove")
                        .WithMany()
                        .HasForeignKey("GameInMoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Domain.MoveLearningMethod", "Method")
                        .WithMany("PokemonMoves")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Domain.Pokemon", "Pokemon")
                        .WithMany("Moves")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameMove");

                    b.Navigation("Method");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Save", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Domain.Game", "Game")
                        .WithMany("Saves")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Domain.SaveTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Domain.User", "User")
                        .WithMany("Saves")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.SaveBox", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Domain.Save", "Save")
                        .WithMany("Boxes")
                        .HasForeignKey("SaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Save");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.SaveBoxSlot", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Domain.SaveBox", "Box")
                        .WithMany("Slots")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Domain.PokemonInstance", "PokemonInstance")
                        .WithMany("BoxSlots")
                        .HasForeignKey("PokemonInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");

                    b.Navigation("PokemonInstance");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.SaveTeam", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Domain.Save", "Save")
                        .WithMany()
                        .HasForeignKey("SaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Save");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.SaveTeamMember", b =>
                {
                    b.HasOne("PokeSaveRomManager.Data.Domain.PokemonInstance", "PokemonInstance")
                        .WithMany("TeamMembers")
                        .HasForeignKey("PokemonInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeSaveRomManager.Data.Domain.SaveTeam", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PokemonInstance");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Ability", b =>
                {
                    b.Navigation("GameAbilities");

                    b.Navigation("PokemonAbilities");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.AbilityName", b =>
                {
                    b.Navigation("Abilities");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Category", b =>
                {
                    b.Navigation("Moves");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Game", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Moves");

                    b.Navigation("Pokemon");

                    b.Navigation("Saves");

                    b.Navigation("Types");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Item", b =>
                {
                    b.Navigation("PokemonInstances");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Move", b =>
                {
                    b.Navigation("GameMoves");

                    b.Navigation("PokemonInstancesWithMove1");

                    b.Navigation("PokemonInstancesWithMove2");

                    b.Navigation("PokemonInstancesWithMove3");

                    b.Navigation("PokemonInstancesWithMove4");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.MoveLearningMethod", b =>
                {
                    b.Navigation("PokemonMoves");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.MoveName", b =>
                {
                    b.Navigation("Moves");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Nature", b =>
                {
                    b.Navigation("PokemonInstances");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Pokemon", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Forms");

                    b.Navigation("Instances");

                    b.Navigation("Moves");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.PokemonForm", b =>
                {
                    b.Navigation("PokemonInstances");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.PokemonInstance", b =>
                {
                    b.Navigation("BoxSlots");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Save", b =>
                {
                    b.Navigation("Boxes");

                    b.Navigation("PokemonInstances");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.SaveBox", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.SaveTeam", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Stat", b =>
                {
                    b.Navigation("DecreasedNatures");

                    b.Navigation("IncreasedNatures");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.Type", b =>
                {
                    b.Navigation("GameTypes");

                    b.Navigation("Moves");
                });

            modelBuilder.Entity("PokeSaveRomManager.Data.Domain.User", b =>
                {
                    b.Navigation("Saves");
                });
#pragma warning restore 612, 618
        }
    }
}
