--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
-- SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Abilities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Abilities" (
    "Id" integer NOT NULL,
    "NameId" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."Abilities" OWNER TO postgres;

--
-- Name: Abilities_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Abilities" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Abilities_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AbilityNames; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AbilityNames" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."AbilityNames" OWNER TO postgres;

--
-- Name: AbilityNames_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AbilityNames" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AbilityNames_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Categories" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."Categories" OWNER TO postgres;

--
-- Name: Categories_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Categories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: GameAbilities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."GameAbilities" (
    "Id" integer NOT NULL,
    "AbilityId" integer NOT NULL,
    "GameId" integer NOT NULL,
    "AbilityInGameId" integer NOT NULL
);


ALTER TABLE public."GameAbilities" OWNER TO postgres;

--
-- Name: GameAbilities_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."GameAbilities" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."GameAbilities_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: GameMoves; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."GameMoves" (
    "Id" integer NOT NULL,
    "MoveId" integer NOT NULL,
    "GameId" integer NOT NULL,
    "MoveInGameId" integer NOT NULL
);


ALTER TABLE public."GameMoves" OWNER TO postgres;

--
-- Name: GameTypes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."GameTypes" (
    "Id" integer NOT NULL,
    "TypeId" integer NOT NULL,
    "GameId" integer NOT NULL,
    "TypeInGameId" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."GameTypes" OWNER TO postgres;

--
-- Name: Games; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Games" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Generation" integer NOT NULL,
    "Official" boolean NOT NULL,
    "Region" text
);


ALTER TABLE public."Games" OWNER TO postgres;

--
-- Name: Games_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Games" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Games_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Items" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."Items" OWNER TO postgres;

--
-- Name: Items_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Items" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Items_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MoveGame_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."GameMoves" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MoveGame_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MoveLearningMethods; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MoveLearningMethods" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."MoveLearningMethods" OWNER TO postgres;

--
-- Name: MoveLearningMethods_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."MoveLearningMethods" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MoveLearningMethods_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MoveNames; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MoveNames" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."MoveNames" OWNER TO postgres;

--
-- Name: MoveNames_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."MoveNames" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MoveNames_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Moves; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Moves" (
    "Id" integer NOT NULL,
    "TypeId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "Power" integer,
    "Accuracy" integer,
    "PP" integer,
    "Effect" text,
    "Priority" integer NOT NULL,
    "NameId" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."Moves" OWNER TO postgres;

--
-- Name: Moves_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Moves" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Moves_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Natures; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Natures" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "IncreasedStatId" integer,
    "DecreasedStatId" integer
);


ALTER TABLE public."Natures" OWNER TO postgres;

--
-- Name: Natures_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Natures" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Natures_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Pokemon; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Pokemon" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "DexNumber" integer NOT NULL,
    "GameId" integer NOT NULL
);


ALTER TABLE public."Pokemon" OWNER TO postgres;

--
-- Name: PokemonAbilities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PokemonAbilities" (
    "Id" integer NOT NULL,
    "PokemonId" integer NOT NULL,
    "AbilityId" integer NOT NULL,
    "IsHidden" boolean NOT NULL,
    "AbilitySlot" integer NOT NULL
);


ALTER TABLE public."PokemonAbilities" OWNER TO postgres;

--
-- Name: PokemonAbilities_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PokemonAbilities" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PokemonAbilities_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PokemonForms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PokemonForms" (
    "Id" integer NOT NULL,
    "PokemonId" integer NOT NULL,
    "Name" text NOT NULL,
    "IsRegional" boolean NOT NULL,
    "IsMega" boolean NOT NULL,
    "IsGigantamax" boolean NOT NULL,
    "Special" integer,
    "Type1Id" integer NOT NULL,
    "Type2Id" integer,
    "Attack" integer DEFAULT 0 NOT NULL,
    "Defense" integer DEFAULT 0 NOT NULL,
    "HP" integer DEFAULT 0 NOT NULL,
    "InternalId" integer,
    "IsDefault" boolean DEFAULT false NOT NULL,
    "SpAttack" integer,
    "SpDefense" integer,
    "Speed" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."PokemonForms" OWNER TO postgres;

--
-- Name: PokemonForms_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PokemonForms" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PokemonForms_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PokemonInstances; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PokemonInstances" (
    "Id" integer NOT NULL,
    "SaveId" integer NOT NULL,
    "PokemonId" integer NOT NULL,
    "FormId" integer DEFAULT 0 NOT NULL,
    "Nickname" text,
    "Gender" character varying(10) NOT NULL,
    "Level" integer NOT NULL,
    "Shiny" boolean NOT NULL,
    "NatureId" integer,
    "HeldItemId" integer,
    "AbilityId" integer,
    "Move1Id" integer,
    "Move2Id" integer,
    "Move3Id" integer,
    "Move4Id" integer,
    "IVHP" integer,
    "IVAttack" integer,
    "IVDefense" integer,
    "IVSpAttack" integer,
    "IVSpDefense" integer,
    "IVSpeed" integer,
    "EVHP" integer,
    "EVAttack" integer,
    "EVDefense" integer,
    "EVSpAttack" integer,
    "EVSpDefense" integer,
    "EVSpeed" integer,
    "MoveId" integer,
    "MoveId1" integer,
    "MoveId2" integer,
    "MoveId3" integer,
    "EVSpecial" integer,
    "IVSpecial" integer
);


ALTER TABLE public."PokemonInstances" OWNER TO postgres;

--
-- Name: PokemonInstances_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PokemonInstances" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PokemonInstances_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PokemonMove; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PokemonMove" (
    "Id" integer NOT NULL,
    "PokemonId" integer NOT NULL,
    "GameInMoveId" integer NOT NULL,
    "MethodId" integer NOT NULL,
    "Level" integer,
    "TMNumber" text,
    "IsTutor" boolean NOT NULL,
    "IsEggMove" boolean NOT NULL
);


ALTER TABLE public."PokemonMove" OWNER TO postgres;

--
-- Name: PokemonMove_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PokemonMove" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PokemonMove_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Pokemon_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Pokemon" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Pokemon_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SaveBoxSlots; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SaveBoxSlots" (
    "Id" integer NOT NULL,
    "BoxId" integer NOT NULL,
    "PokemonInstanceId" integer NOT NULL,
    "SlotNumber" integer NOT NULL
);


ALTER TABLE public."SaveBoxSlots" OWNER TO postgres;

--
-- Name: SaveBoxSlots_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SaveBoxSlots" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SaveBoxSlots_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SaveBoxes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SaveBoxes" (
    "Id" integer NOT NULL,
    "SaveId" integer NOT NULL,
    "Name" text
);


ALTER TABLE public."SaveBoxes" OWNER TO postgres;

--
-- Name: SaveBoxes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SaveBoxes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SaveBoxes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SaveTeamMembers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SaveTeamMembers" (
    "Id" integer NOT NULL,
    "TeamId" integer NOT NULL,
    "PokemonInstanceId" integer NOT NULL
);


ALTER TABLE public."SaveTeamMembers" OWNER TO postgres;

--
-- Name: SaveTeamMembers_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SaveTeamMembers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SaveTeamMembers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SaveTeams; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SaveTeams" (
    "Id" integer NOT NULL,
    "SaveId" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."SaveTeams" OWNER TO postgres;

--
-- Name: SaveTeams_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SaveTeams" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SaveTeams_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Saves; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Saves" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "GameId" integer NOT NULL,
    "TeamId" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."Saves" OWNER TO postgres;

--
-- Name: Saves_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Saves" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Saves_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Stats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Stats" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."Stats" OWNER TO postgres;

--
-- Name: Stats_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Stats" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Stats_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: TypeGame_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."GameTypes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TypeGame_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Types" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."Types" OWNER TO postgres;

--
-- Name: Types_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Types" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Types_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Auth0Id" text DEFAULT ''::text NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Abilities; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Abilities" ("Id", "NameId") FROM stdin;
\.


--
-- Data for Name: AbilityNames; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AbilityNames" ("Id", "Name") FROM stdin;
\.


--
-- Data for Name: Categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Categories" ("Id", "Name") FROM stdin;
\.


--
-- Data for Name: GameAbilities; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."GameAbilities" ("Id", "AbilityId", "GameId", "AbilityInGameId") FROM stdin;
\.


--
-- Data for Name: GameMoves; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."GameMoves" ("Id", "MoveId", "GameId", "MoveInGameId") FROM stdin;
\.


--
-- Data for Name: GameTypes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."GameTypes" ("Id", "TypeId", "GameId", "TypeInGameId") FROM stdin;
\.


--
-- Data for Name: Games; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Games" ("Id", "Name", "Generation", "Official", "Region") FROM stdin;
\.


--
-- Data for Name: Items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Items" ("Id", "Name") FROM stdin;
\.


--
-- Data for Name: MoveLearningMethods; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."MoveLearningMethods" ("Id", "Name") FROM stdin;
\.


--
-- Data for Name: MoveNames; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."MoveNames" ("Id", "Name") FROM stdin;
\.


--
-- Data for Name: Moves; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Moves" ("Id", "TypeId", "CategoryId", "Power", "Accuracy", "PP", "Effect", "Priority", "NameId") FROM stdin;
\.


--
-- Data for Name: Natures; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Natures" ("Id", "Name", "IncreasedStatId", "DecreasedStatId") FROM stdin;
\.


--
-- Data for Name: Pokemon; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Pokemon" ("Id", "Name", "DexNumber", "GameId") FROM stdin;
\.


--
-- Data for Name: PokemonAbilities; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."PokemonAbilities" ("Id", "PokemonId", "AbilityId", "IsHidden", "AbilitySlot") FROM stdin;
\.


--
-- Data for Name: PokemonForms; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."PokemonForms" ("Id", "PokemonId", "Name", "IsRegional", "IsMega", "IsGigantamax", "Special", "Type1Id", "Type2Id", "Attack", "Defense", "HP", "InternalId", "IsDefault", "SpAttack", "SpDefense", "Speed") FROM stdin;
\.


--
-- Data for Name: PokemonInstances; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."PokemonInstances" ("Id", "SaveId", "PokemonId", "FormId", "Nickname", "Gender", "Level", "Shiny", "NatureId", "HeldItemId", "AbilityId", "Move1Id", "Move2Id", "Move3Id", "Move4Id", "IVHP", "IVAttack", "IVDefense", "IVSpAttack", "IVSpDefense", "IVSpeed", "EVHP", "EVAttack", "EVDefense", "EVSpAttack", "EVSpDefense", "EVSpeed", "MoveId", "MoveId1", "MoveId2", "MoveId3", "EVSpecial", "IVSpecial") FROM stdin;
\.


--
-- Data for Name: PokemonMove; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."PokemonMove" ("Id", "PokemonId", "GameInMoveId", "MethodId", "Level", "TMNumber", "IsTutor", "IsEggMove") FROM stdin;
\.


--
-- Data for Name: SaveBoxSlots; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."SaveBoxSlots" ("Id", "BoxId", "PokemonInstanceId", "SlotNumber") FROM stdin;
\.


--
-- Data for Name: SaveBoxes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."SaveBoxes" ("Id", "SaveId", "Name") FROM stdin;
\.


--
-- Data for Name: SaveTeamMembers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."SaveTeamMembers" ("Id", "TeamId", "PokemonInstanceId") FROM stdin;
\.


--
-- Data for Name: SaveTeams; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."SaveTeams" ("Id", "SaveId", "Name", "Description", "CreatedAt") FROM stdin;
\.


--
-- Data for Name: Saves; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Saves" ("Id", "UserId", "GameId", "TeamId") FROM stdin;
\.


--
-- Data for Name: Stats; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Stats" ("Id", "Name") FROM stdin;
\.


--
-- Data for Name: Types; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Types" ("Id", "Name") FROM stdin;
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Name", "Email", "Auth0Id", "CreatedAt", "UpdatedAt") FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250417080158_InitialCreate	9.0.4
20250418150732_AddAuth0Id	9.0.4
20250421192716_MoveGame	9.0.4
20250422093137_MoveGame-MoveLearning	9.0.4
20250422130317_pending	9.0.4
20250422134013_TypeGame	9.0.4
20250423060517_package-renaming	9.0.4
20250423133613_AddedSpecialStatForGen1	9.0.4
20250423183048_MoveGame-Table	9.0.4
20250424174523_MoveName	9.0.4
20250425092329_AbilityTables	9.0.4
20250425111608_Refactor-GameTables	9.0.4
20250425171653_Rename-dGameTables	9.0.4
20250428081642_Renamed-Pokemon-Related-Tables	9.0.4
20250428121422_Saves	9.0.4
20250428212240_Fix-SavesBox-Relation	9.0.4
20250428214106_Fix-Saves-UserId-Index	9.0.4
20250428214323_User-NavProperties	9.0.4
20250503173337_ChangedPokemonFormRelations	9.0.4
20250512213159_AutoincrementOnKeys	9.0.4
20250514162802_FixNatureStatRelation	9.0.4
\.


--
-- Name: Abilities_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Abilities_Id_seq"', 1, false);


--
-- Name: AbilityNames_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AbilityNames_Id_seq"', 1, false);


--
-- Name: Categories_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Categories_Id_seq"', 1, false);


--
-- Name: GameAbilities_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."GameAbilities_Id_seq"', 1, false);


--
-- Name: Games_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Games_Id_seq"', 1, false);


--
-- Name: Items_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Items_Id_seq"', 1, false);


--
-- Name: MoveGame_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."MoveGame_Id_seq"', 1, false);


--
-- Name: MoveLearningMethods_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."MoveLearningMethods_Id_seq"', 1, false);


--
-- Name: MoveNames_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."MoveNames_Id_seq"', 1, false);


--
-- Name: Moves_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Moves_Id_seq"', 1, false);


--
-- Name: Natures_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Natures_Id_seq"', 1, false);


--
-- Name: PokemonAbilities_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."PokemonAbilities_Id_seq"', 1, false);


--
-- Name: PokemonForms_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."PokemonForms_Id_seq"', 1, false);


--
-- Name: PokemonInstances_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."PokemonInstances_Id_seq"', 1, false);


--
-- Name: PokemonMove_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."PokemonMove_Id_seq"', 1, false);


--
-- Name: Pokemon_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Pokemon_Id_seq"', 1, false);


--
-- Name: SaveBoxSlots_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SaveBoxSlots_Id_seq"', 1, false);


--
-- Name: SaveBoxes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SaveBoxes_Id_seq"', 1, false);


--
-- Name: SaveTeamMembers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SaveTeamMembers_Id_seq"', 1, false);


--
-- Name: SaveTeams_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SaveTeams_Id_seq"', 1, false);


--
-- Name: Saves_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Saves_Id_seq"', 1, false);


--
-- Name: Stats_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Stats_Id_seq"', 1, false);


--
-- Name: TypeGame_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."TypeGame_Id_seq"', 1, false);


--
-- Name: Types_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Types_Id_seq"', 1, false);


--
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 1, false);


--
-- Name: Abilities PK_Abilities; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Abilities"
    ADD CONSTRAINT "PK_Abilities" PRIMARY KEY ("Id");


--
-- Name: AbilityNames PK_AbilityNames; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AbilityNames"
    ADD CONSTRAINT "PK_AbilityNames" PRIMARY KEY ("Id");


--
-- Name: Categories PK_Categories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("Id");


--
-- Name: GameAbilities PK_GameAbilities; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GameAbilities"
    ADD CONSTRAINT "PK_GameAbilities" PRIMARY KEY ("Id");


--
-- Name: GameMoves PK_GameMoves; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GameMoves"
    ADD CONSTRAINT "PK_GameMoves" PRIMARY KEY ("Id");


--
-- Name: GameTypes PK_GameTypes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GameTypes"
    ADD CONSTRAINT "PK_GameTypes" PRIMARY KEY ("Id");


--
-- Name: Games PK_Games; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Games"
    ADD CONSTRAINT "PK_Games" PRIMARY KEY ("Id");


--
-- Name: Items PK_Items; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Items"
    ADD CONSTRAINT "PK_Items" PRIMARY KEY ("Id");


--
-- Name: MoveLearningMethods PK_MoveLearningMethods; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MoveLearningMethods"
    ADD CONSTRAINT "PK_MoveLearningMethods" PRIMARY KEY ("Id");


--
-- Name: MoveNames PK_MoveNames; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MoveNames"
    ADD CONSTRAINT "PK_MoveNames" PRIMARY KEY ("Id");


--
-- Name: Moves PK_Moves; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Moves"
    ADD CONSTRAINT "PK_Moves" PRIMARY KEY ("Id");


--
-- Name: Natures PK_Natures; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Natures"
    ADD CONSTRAINT "PK_Natures" PRIMARY KEY ("Id");


--
-- Name: Pokemon PK_Pokemon; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Pokemon"
    ADD CONSTRAINT "PK_Pokemon" PRIMARY KEY ("Id");


--
-- Name: PokemonAbilities PK_PokemonAbilities; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonAbilities"
    ADD CONSTRAINT "PK_PokemonAbilities" PRIMARY KEY ("Id");


--
-- Name: PokemonForms PK_PokemonForms; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonForms"
    ADD CONSTRAINT "PK_PokemonForms" PRIMARY KEY ("Id");


--
-- Name: PokemonInstances PK_PokemonInstances; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonInstances"
    ADD CONSTRAINT "PK_PokemonInstances" PRIMARY KEY ("Id");


--
-- Name: PokemonMove PK_PokemonMove; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonMove"
    ADD CONSTRAINT "PK_PokemonMove" PRIMARY KEY ("Id");


--
-- Name: SaveBoxSlots PK_SaveBoxSlots; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SaveBoxSlots"
    ADD CONSTRAINT "PK_SaveBoxSlots" PRIMARY KEY ("Id");


--
-- Name: SaveBoxes PK_SaveBoxes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SaveBoxes"
    ADD CONSTRAINT "PK_SaveBoxes" PRIMARY KEY ("Id");


--
-- Name: SaveTeamMembers PK_SaveTeamMembers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SaveTeamMembers"
    ADD CONSTRAINT "PK_SaveTeamMembers" PRIMARY KEY ("Id");


--
-- Name: SaveTeams PK_SaveTeams; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SaveTeams"
    ADD CONSTRAINT "PK_SaveTeams" PRIMARY KEY ("Id");


--
-- Name: Saves PK_Saves; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Saves"
    ADD CONSTRAINT "PK_Saves" PRIMARY KEY ("Id");


--
-- Name: Stats PK_Stats; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Stats"
    ADD CONSTRAINT "PK_Stats" PRIMARY KEY ("Id");


--
-- Name: Types PK_Types; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Types"
    ADD CONSTRAINT "PK_Types" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Abilities_NameId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Abilities_NameId" ON public."Abilities" USING btree ("NameId");


--
-- Name: IX_GameAbilities_AbilityId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_GameAbilities_AbilityId" ON public."GameAbilities" USING btree ("AbilityId");


--
-- Name: IX_GameAbilities_GameId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_GameAbilities_GameId" ON public."GameAbilities" USING btree ("GameId");


--
-- Name: IX_GameMoves_GameId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_GameMoves_GameId" ON public."GameMoves" USING btree ("GameId");


--
-- Name: IX_GameMoves_MoveId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_GameMoves_MoveId" ON public."GameMoves" USING btree ("MoveId");


--
-- Name: IX_GameTypes_GameId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_GameTypes_GameId" ON public."GameTypes" USING btree ("GameId");


--
-- Name: IX_GameTypes_TypeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_GameTypes_TypeId" ON public."GameTypes" USING btree ("TypeId");


--
-- Name: IX_Moves_CategoryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Moves_CategoryId" ON public."Moves" USING btree ("CategoryId");


--
-- Name: IX_Moves_NameId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Moves_NameId" ON public."Moves" USING btree ("NameId");


--
-- Name: IX_Moves_TypeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Moves_TypeId" ON public."Moves" USING btree ("TypeId");


--
-- Name: IX_Natures_DecreasedStatId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Natures_DecreasedStatId" ON public."Natures" USING btree ("DecreasedStatId");


--
-- Name: IX_Natures_IncreasedStatId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Natures_IncreasedStatId" ON public."Natures" USING btree ("IncreasedStatId");


--
-- Name: IX_PokemonAbilities_AbilityId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonAbilities_AbilityId" ON public."PokemonAbilities" USING btree ("AbilityId");


--
-- Name: IX_PokemonAbilities_PokemonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonAbilities_PokemonId" ON public."PokemonAbilities" USING btree ("PokemonId");


--
-- Name: IX_PokemonForms_PokemonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonForms_PokemonId" ON public."PokemonForms" USING btree ("PokemonId");


--
-- Name: IX_PokemonForms_Type1Id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonForms_Type1Id" ON public."PokemonForms" USING btree ("Type1Id");


--
-- Name: IX_PokemonForms_Type2Id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonForms_Type2Id" ON public."PokemonForms" USING btree ("Type2Id");


--
-- Name: IX_PokemonInstances_AbilityId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonInstances_AbilityId" ON public."PokemonInstances" USING btree ("AbilityId");


--
-- Name: IX_PokemonInstances_FormId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonInstances_FormId" ON public."PokemonInstances" USING btree ("FormId");


--
-- Name: IX_PokemonInstances_HeldItemId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonInstances_HeldItemId" ON public."PokemonInstances" USING btree ("HeldItemId");


--
-- Name: IX_PokemonInstances_Move1Id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonInstances_Move1Id" ON public."PokemonInstances" USING btree ("Move1Id");


--
-- Name: IX_PokemonInstances_Move2Id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonInstances_Move2Id" ON public."PokemonInstances" USING btree ("Move2Id");


--
-- Name: IX_PokemonInstances_Move3Id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonInstances_Move3Id" ON public."PokemonInstances" USING btree ("Move3Id");


--
-- Name: IX_PokemonInstances_Move4Id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonInstances_Move4Id" ON public."PokemonInstances" USING btree ("Move4Id");


--
-- Name: IX_PokemonInstances_MoveId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonInstances_MoveId" ON public."PokemonInstances" USING btree ("MoveId");


--
-- Name: IX_PokemonInstances_MoveId1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonInstances_MoveId1" ON public."PokemonInstances" USING btree ("MoveId1");


--
-- Name: IX_PokemonInstances_MoveId2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonInstances_MoveId2" ON public."PokemonInstances" USING btree ("MoveId2");


--
-- Name: IX_PokemonInstances_MoveId3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonInstances_MoveId3" ON public."PokemonInstances" USING btree ("MoveId3");


--
-- Name: IX_PokemonInstances_NatureId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonInstances_NatureId" ON public."PokemonInstances" USING btree ("NatureId");


--
-- Name: IX_PokemonInstances_PokemonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonInstances_PokemonId" ON public."PokemonInstances" USING btree ("PokemonId");


--
-- Name: IX_PokemonInstances_SaveId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonInstances_SaveId" ON public."PokemonInstances" USING btree ("SaveId");


--
-- Name: IX_PokemonMove_GameInMoveId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonMove_GameInMoveId" ON public."PokemonMove" USING btree ("GameInMoveId");


--
-- Name: IX_PokemonMove_MethodId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonMove_MethodId" ON public."PokemonMove" USING btree ("MethodId");


--
-- Name: IX_PokemonMove_PokemonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PokemonMove_PokemonId" ON public."PokemonMove" USING btree ("PokemonId");


--
-- Name: IX_Pokemon_GameId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Pokemon_GameId" ON public."Pokemon" USING btree ("GameId");


--
-- Name: IX_SaveBoxSlots_BoxId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SaveBoxSlots_BoxId" ON public."SaveBoxSlots" USING btree ("BoxId");


--
-- Name: IX_SaveBoxSlots_PokemonInstanceId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SaveBoxSlots_PokemonInstanceId" ON public."SaveBoxSlots" USING btree ("PokemonInstanceId");


--
-- Name: IX_SaveBoxes_SaveId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SaveBoxes_SaveId" ON public."SaveBoxes" USING btree ("SaveId");


--
-- Name: IX_SaveTeamMembers_PokemonInstanceId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SaveTeamMembers_PokemonInstanceId" ON public."SaveTeamMembers" USING btree ("PokemonInstanceId");


--
-- Name: IX_SaveTeamMembers_TeamId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SaveTeamMembers_TeamId" ON public."SaveTeamMembers" USING btree ("TeamId");


--
-- Name: IX_SaveTeams_SaveId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SaveTeams_SaveId" ON public."SaveTeams" USING btree ("SaveId");


--
-- Name: IX_Saves_GameId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Saves_GameId" ON public."Saves" USING btree ("GameId");


--
-- Name: IX_Saves_TeamId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Saves_TeamId" ON public."Saves" USING btree ("TeamId");


--
-- Name: IX_Saves_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Saves_UserId" ON public."Saves" USING btree ("UserId");


--
-- Name: IX_Users_Auth0Id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Auth0Id" ON public."Users" USING btree ("Auth0Id");


--
-- Name: Abilities FK_Abilities_AbilityNames_NameId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Abilities"
    ADD CONSTRAINT "FK_Abilities_AbilityNames_NameId" FOREIGN KEY ("NameId") REFERENCES public."AbilityNames"("Id") ON DELETE CASCADE;


--
-- Name: GameAbilities FK_GameAbilities_Abilities_AbilityId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GameAbilities"
    ADD CONSTRAINT "FK_GameAbilities_Abilities_AbilityId" FOREIGN KEY ("AbilityId") REFERENCES public."Abilities"("Id") ON DELETE CASCADE;


--
-- Name: GameAbilities FK_GameAbilities_Games_GameId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GameAbilities"
    ADD CONSTRAINT "FK_GameAbilities_Games_GameId" FOREIGN KEY ("GameId") REFERENCES public."Games"("Id") ON DELETE CASCADE;


--
-- Name: GameMoves FK_GameMoves_Games_GameId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GameMoves"
    ADD CONSTRAINT "FK_GameMoves_Games_GameId" FOREIGN KEY ("GameId") REFERENCES public."Games"("Id") ON DELETE CASCADE;


--
-- Name: GameMoves FK_GameMoves_Moves_MoveId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GameMoves"
    ADD CONSTRAINT "FK_GameMoves_Moves_MoveId" FOREIGN KEY ("MoveId") REFERENCES public."Moves"("Id") ON DELETE CASCADE;


--
-- Name: GameTypes FK_GameTypes_Games_GameId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GameTypes"
    ADD CONSTRAINT "FK_GameTypes_Games_GameId" FOREIGN KEY ("GameId") REFERENCES public."Games"("Id") ON DELETE CASCADE;


--
-- Name: GameTypes FK_GameTypes_Types_TypeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."GameTypes"
    ADD CONSTRAINT "FK_GameTypes_Types_TypeId" FOREIGN KEY ("TypeId") REFERENCES public."Types"("Id") ON DELETE CASCADE;


--
-- Name: Moves FK_Moves_Categories_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Moves"
    ADD CONSTRAINT "FK_Moves_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("Id") ON DELETE CASCADE;


--
-- Name: Moves FK_Moves_MoveNames_NameId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Moves"
    ADD CONSTRAINT "FK_Moves_MoveNames_NameId" FOREIGN KEY ("NameId") REFERENCES public."MoveNames"("Id") ON DELETE CASCADE;


--
-- Name: Moves FK_Moves_Types_TypeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Moves"
    ADD CONSTRAINT "FK_Moves_Types_TypeId" FOREIGN KEY ("TypeId") REFERENCES public."Types"("Id") ON DELETE CASCADE;


--
-- Name: Natures FK_Natures_Stats_DecreasedStatId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Natures"
    ADD CONSTRAINT "FK_Natures_Stats_DecreasedStatId" FOREIGN KEY ("DecreasedStatId") REFERENCES public."Stats"("Id") ON DELETE RESTRICT;


--
-- Name: Natures FK_Natures_Stats_IncreasedStatId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Natures"
    ADD CONSTRAINT "FK_Natures_Stats_IncreasedStatId" FOREIGN KEY ("IncreasedStatId") REFERENCES public."Stats"("Id") ON DELETE RESTRICT;


--
-- Name: PokemonAbilities FK_PokemonAbilities_Abilities_AbilityId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonAbilities"
    ADD CONSTRAINT "FK_PokemonAbilities_Abilities_AbilityId" FOREIGN KEY ("AbilityId") REFERENCES public."Abilities"("Id") ON DELETE CASCADE;


--
-- Name: PokemonAbilities FK_PokemonAbilities_Pokemon_PokemonId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonAbilities"
    ADD CONSTRAINT "FK_PokemonAbilities_Pokemon_PokemonId" FOREIGN KEY ("PokemonId") REFERENCES public."Pokemon"("Id") ON DELETE CASCADE;


--
-- Name: PokemonForms FK_PokemonForms_Pokemon_PokemonId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonForms"
    ADD CONSTRAINT "FK_PokemonForms_Pokemon_PokemonId" FOREIGN KEY ("PokemonId") REFERENCES public."Pokemon"("Id") ON DELETE CASCADE;


--
-- Name: PokemonForms FK_PokemonForms_Types_Type1Id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonForms"
    ADD CONSTRAINT "FK_PokemonForms_Types_Type1Id" FOREIGN KEY ("Type1Id") REFERENCES public."Types"("Id") ON DELETE RESTRICT;


--
-- Name: PokemonForms FK_PokemonForms_Types_Type2Id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonForms"
    ADD CONSTRAINT "FK_PokemonForms_Types_Type2Id" FOREIGN KEY ("Type2Id") REFERENCES public."Types"("Id") ON DELETE RESTRICT;


--
-- Name: PokemonInstances FK_PokemonInstances_Abilities_AbilityId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonInstances"
    ADD CONSTRAINT "FK_PokemonInstances_Abilities_AbilityId" FOREIGN KEY ("AbilityId") REFERENCES public."Abilities"("Id");


--
-- Name: PokemonInstances FK_PokemonInstances_Items_HeldItemId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonInstances"
    ADD CONSTRAINT "FK_PokemonInstances_Items_HeldItemId" FOREIGN KEY ("HeldItemId") REFERENCES public."Items"("Id");


--
-- Name: PokemonInstances FK_PokemonInstances_Moves_Move1Id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonInstances"
    ADD CONSTRAINT "FK_PokemonInstances_Moves_Move1Id" FOREIGN KEY ("Move1Id") REFERENCES public."Moves"("Id") ON DELETE RESTRICT;


--
-- Name: PokemonInstances FK_PokemonInstances_Moves_Move2Id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonInstances"
    ADD CONSTRAINT "FK_PokemonInstances_Moves_Move2Id" FOREIGN KEY ("Move2Id") REFERENCES public."Moves"("Id") ON DELETE RESTRICT;


--
-- Name: PokemonInstances FK_PokemonInstances_Moves_Move3Id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonInstances"
    ADD CONSTRAINT "FK_PokemonInstances_Moves_Move3Id" FOREIGN KEY ("Move3Id") REFERENCES public."Moves"("Id") ON DELETE RESTRICT;


--
-- Name: PokemonInstances FK_PokemonInstances_Moves_Move4Id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonInstances"
    ADD CONSTRAINT "FK_PokemonInstances_Moves_Move4Id" FOREIGN KEY ("Move4Id") REFERENCES public."Moves"("Id") ON DELETE RESTRICT;


--
-- Name: PokemonInstances FK_PokemonInstances_Moves_MoveId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonInstances"
    ADD CONSTRAINT "FK_PokemonInstances_Moves_MoveId" FOREIGN KEY ("MoveId") REFERENCES public."Moves"("Id");


--
-- Name: PokemonInstances FK_PokemonInstances_Moves_MoveId1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonInstances"
    ADD CONSTRAINT "FK_PokemonInstances_Moves_MoveId1" FOREIGN KEY ("MoveId1") REFERENCES public."Moves"("Id");


--
-- Name: PokemonInstances FK_PokemonInstances_Moves_MoveId2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonInstances"
    ADD CONSTRAINT "FK_PokemonInstances_Moves_MoveId2" FOREIGN KEY ("MoveId2") REFERENCES public."Moves"("Id");


--
-- Name: PokemonInstances FK_PokemonInstances_Moves_MoveId3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonInstances"
    ADD CONSTRAINT "FK_PokemonInstances_Moves_MoveId3" FOREIGN KEY ("MoveId3") REFERENCES public."Moves"("Id");


--
-- Name: PokemonInstances FK_PokemonInstances_Natures_NatureId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonInstances"
    ADD CONSTRAINT "FK_PokemonInstances_Natures_NatureId" FOREIGN KEY ("NatureId") REFERENCES public."Natures"("Id");


--
-- Name: PokemonInstances FK_PokemonInstances_PokemonForms_FormId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonInstances"
    ADD CONSTRAINT "FK_PokemonInstances_PokemonForms_FormId" FOREIGN KEY ("FormId") REFERENCES public."PokemonForms"("Id") ON DELETE CASCADE;


--
-- Name: PokemonInstances FK_PokemonInstances_Pokemon_PokemonId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonInstances"
    ADD CONSTRAINT "FK_PokemonInstances_Pokemon_PokemonId" FOREIGN KEY ("PokemonId") REFERENCES public."Pokemon"("Id") ON DELETE CASCADE;


--
-- Name: PokemonInstances FK_PokemonInstances_Saves_SaveId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonInstances"
    ADD CONSTRAINT "FK_PokemonInstances_Saves_SaveId" FOREIGN KEY ("SaveId") REFERENCES public."Saves"("Id") ON DELETE CASCADE;


--
-- Name: PokemonMove FK_PokemonMove_GameMoves_GameInMoveId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonMove"
    ADD CONSTRAINT "FK_PokemonMove_GameMoves_GameInMoveId" FOREIGN KEY ("GameInMoveId") REFERENCES public."GameMoves"("Id") ON DELETE CASCADE;


--
-- Name: PokemonMove FK_PokemonMove_MoveLearningMethods_MethodId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonMove"
    ADD CONSTRAINT "FK_PokemonMove_MoveLearningMethods_MethodId" FOREIGN KEY ("MethodId") REFERENCES public."MoveLearningMethods"("Id") ON DELETE CASCADE;


--
-- Name: PokemonMove FK_PokemonMove_Pokemon_PokemonId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PokemonMove"
    ADD CONSTRAINT "FK_PokemonMove_Pokemon_PokemonId" FOREIGN KEY ("PokemonId") REFERENCES public."Pokemon"("Id") ON DELETE CASCADE;


--
-- Name: Pokemon FK_Pokemon_Games_GameId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Pokemon"
    ADD CONSTRAINT "FK_Pokemon_Games_GameId" FOREIGN KEY ("GameId") REFERENCES public."Games"("Id") ON DELETE CASCADE;


--
-- Name: SaveBoxSlots FK_SaveBoxSlots_PokemonInstances_PokemonInstanceId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SaveBoxSlots"
    ADD CONSTRAINT "FK_SaveBoxSlots_PokemonInstances_PokemonInstanceId" FOREIGN KEY ("PokemonInstanceId") REFERENCES public."PokemonInstances"("Id") ON DELETE CASCADE;


--
-- Name: SaveBoxSlots FK_SaveBoxSlots_SaveBoxes_BoxId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SaveBoxSlots"
    ADD CONSTRAINT "FK_SaveBoxSlots_SaveBoxes_BoxId" FOREIGN KEY ("BoxId") REFERENCES public."SaveBoxes"("Id") ON DELETE CASCADE;


--
-- Name: SaveBoxes FK_SaveBoxes_Saves_SaveId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SaveBoxes"
    ADD CONSTRAINT "FK_SaveBoxes_Saves_SaveId" FOREIGN KEY ("SaveId") REFERENCES public."Saves"("Id") ON DELETE CASCADE;


--
-- Name: SaveTeamMembers FK_SaveTeamMembers_PokemonInstances_PokemonInstanceId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SaveTeamMembers"
    ADD CONSTRAINT "FK_SaveTeamMembers_PokemonInstances_PokemonInstanceId" FOREIGN KEY ("PokemonInstanceId") REFERENCES public."PokemonInstances"("Id") ON DELETE CASCADE;


--
-- Name: SaveTeamMembers FK_SaveTeamMembers_SaveTeams_TeamId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SaveTeamMembers"
    ADD CONSTRAINT "FK_SaveTeamMembers_SaveTeams_TeamId" FOREIGN KEY ("TeamId") REFERENCES public."SaveTeams"("Id") ON DELETE CASCADE;


--
-- Name: SaveTeams FK_SaveTeams_Saves_SaveId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SaveTeams"
    ADD CONSTRAINT "FK_SaveTeams_Saves_SaveId" FOREIGN KEY ("SaveId") REFERENCES public."Saves"("Id") ON DELETE CASCADE;


--
-- Name: Saves FK_Saves_Games_GameId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Saves"
    ADD CONSTRAINT "FK_Saves_Games_GameId" FOREIGN KEY ("GameId") REFERENCES public."Games"("Id") ON DELETE CASCADE;


--
-- Name: Saves FK_Saves_SaveTeams_TeamId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Saves"
    ADD CONSTRAINT "FK_Saves_SaveTeams_TeamId" FOREIGN KEY ("TeamId") REFERENCES public."SaveTeams"("Id") ON DELETE CASCADE;


--
-- Name: Saves FK_Saves_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Saves"
    ADD CONSTRAINT "FK_Saves_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

