CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Abilities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Abilities" PRIMARY KEY ("Id")
);

CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "Games" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Generation" integer NOT NULL,
    "Official" boolean NOT NULL,
    "Region" text NOT NULL,
    CONSTRAINT "PK_Games" PRIMARY KEY ("Id")
);

CREATE TABLE "Items" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Items" PRIMARY KEY ("Id")
);

CREATE TABLE "MoveLearningMethods" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_MoveLearningMethods" PRIMARY KEY ("Id")
);

CREATE TABLE "Stats" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Stats" PRIMARY KEY ("Id")
);

CREATE TABLE "Types" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Types" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Natures" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "IncreasedStatId" integer,
    "DecreasedStatId" integer,
    "StatId" integer,
    "StatId1" integer,
    CONSTRAINT "PK_Natures" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Natures_Stats_DecreasedStatId" FOREIGN KEY ("DecreasedStatId") REFERENCES "Stats" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Natures_Stats_IncreasedStatId" FOREIGN KEY ("IncreasedStatId") REFERENCES "Stats" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Natures_Stats_StatId" FOREIGN KEY ("StatId") REFERENCES "Stats" ("Id"),
    CONSTRAINT "FK_Natures_Stats_StatId1" FOREIGN KEY ("StatId1") REFERENCES "Stats" ("Id")
);

CREATE TABLE "Moves" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "TypeId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "Power" integer,
    "Accuracy" integer,
    "PP" integer,
    "Effect" text NOT NULL,
    "Priority" integer NOT NULL,
    CONSTRAINT "PK_Moves" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Moves_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Moves_Types_TypeId" FOREIGN KEY ("TypeId") REFERENCES "Types" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Pokemon" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "DexNumber" integer NOT NULL,
    "GameId" integer NOT NULL,
    "HP" integer NOT NULL,
    "Attack" integer NOT NULL,
    "Defense" integer NOT NULL,
    "SpAttack" integer NOT NULL,
    "SpDefense" integer NOT NULL,
    "Speed" integer NOT NULL,
    "Type1Id" integer NOT NULL,
    "Type2Id" integer,
    "FormName" text NOT NULL,
    "IsRegionalForm" boolean NOT NULL,
    "IsMega" boolean NOT NULL,
    "IsGigantamax" boolean NOT NULL,
    CONSTRAINT "PK_Pokemon" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Pokemon_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Pokemon_Types_Type1Id" FOREIGN KEY ("Type1Id") REFERENCES "Types" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Pokemon_Types_Type2Id" FOREIGN KEY ("Type2Id") REFERENCES "Types" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Boxes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "GameId" integer NOT NULL,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Boxes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Boxes_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Boxes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Teams" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "GameId" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Teams" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Teams_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Teams_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Forms" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PokemonId" integer NOT NULL,
    "Name" text NOT NULL,
    "IsRegional" boolean NOT NULL,
    "IsMega" boolean NOT NULL,
    "IsGigantamax" boolean NOT NULL,
    "FormOrder" integer,
    "Type1Id" integer NOT NULL,
    "Type2Id" integer,
    CONSTRAINT "PK_Forms" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Forms_Pokemon_PokemonId" FOREIGN KEY ("PokemonId") REFERENCES "Pokemon" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Forms_Types_Type1Id" FOREIGN KEY ("Type1Id") REFERENCES "Types" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Forms_Types_Type2Id" FOREIGN KEY ("Type2Id") REFERENCES "Types" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "MoveLearning" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PokemonId" integer NOT NULL,
    "MoveId" integer NOT NULL,
    "MethodId" integer NOT NULL,
    "GameId" integer NOT NULL,
    "Level" integer,
    "TMNumber" text NOT NULL,
    "IsTutor" boolean NOT NULL,
    "IsEggMove" boolean NOT NULL,
    CONSTRAINT "PK_MoveLearning" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MoveLearning_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MoveLearning_MoveLearningMethods_MethodId" FOREIGN KEY ("MethodId") REFERENCES "MoveLearningMethods" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MoveLearning_Moves_MoveId" FOREIGN KEY ("MoveId") REFERENCES "Moves" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MoveLearning_Pokemon_PokemonId" FOREIGN KEY ("PokemonId") REFERENCES "Pokemon" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PokemonAbilities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PokemonId" integer NOT NULL,
    "AbilityId" integer NOT NULL,
    "IsHidden" boolean NOT NULL,
    "AbilitySlot" integer NOT NULL,
    CONSTRAINT "PK_PokemonAbilities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PokemonAbilities_Abilities_AbilityId" FOREIGN KEY ("AbilityId") REFERENCES "Abilities" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PokemonAbilities_Pokemon_PokemonId" FOREIGN KEY ("PokemonId") REFERENCES "Pokemon" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PokemonInstances" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "GameId" integer NOT NULL,
    "PokemonId" integer NOT NULL,
    "FormId" integer,
    "Nickname" text NOT NULL,
    "Gender" character varying(10) NOT NULL,
    "Level" integer NOT NULL,
    "Shiny" boolean NOT NULL,
    "NatureId" integer,
    "HeldItemId" integer,
    "AbilityId" integer,
    "Move1Id" integer,
    "Move2Id" integer,
    "Move3Id" integer,
    "Move4Id" integer,
    "IVHP" integer,
    "IVAttack" integer,
    "IVDefense" integer,
    "IVSpAttack" integer,
    "IVSpDefense" integer,
    "IVSpeed" integer,
    "EVHP" integer,
    "EVAttack" integer,
    "EVDefense" integer,
    "EVSpAttack" integer,
    "EVSpDefense" integer,
    "EVSpeed" integer,
    "OriginalTrainerName" text NOT NULL,
    "OriginalTrainerId" text NOT NULL,
    "MetLevel" integer,
    "MetLocation" text NOT NULL,
    "Ribbons" text NOT NULL,
    "MoveId" integer,
    "MoveId1" integer,
    "MoveId2" integer,
    "MoveId3" integer,
    CONSTRAINT "PK_PokemonInstances" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PokemonInstances_Abilities_AbilityId" FOREIGN KEY ("AbilityId") REFERENCES "Abilities" ("Id"),
    CONSTRAINT "FK_PokemonInstances_Forms_FormId" FOREIGN KEY ("FormId") REFERENCES "Forms" ("Id"),
    CONSTRAINT "FK_PokemonInstances_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PokemonInstances_Items_HeldItemId" FOREIGN KEY ("HeldItemId") REFERENCES "Items" ("Id"),
    CONSTRAINT "FK_PokemonInstances_Moves_Move1Id" FOREIGN KEY ("Move1Id") REFERENCES "Moves" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PokemonInstances_Moves_Move2Id" FOREIGN KEY ("Move2Id") REFERENCES "Moves" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PokemonInstances_Moves_Move3Id" FOREIGN KEY ("Move3Id") REFERENCES "Moves" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PokemonInstances_Moves_Move4Id" FOREIGN KEY ("Move4Id") REFERENCES "Moves" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PokemonInstances_Moves_MoveId" FOREIGN KEY ("MoveId") REFERENCES "Moves" ("Id"),
    CONSTRAINT "FK_PokemonInstances_Moves_MoveId1" FOREIGN KEY ("MoveId1") REFERENCES "Moves" ("Id"),
    CONSTRAINT "FK_PokemonInstances_Moves_MoveId2" FOREIGN KEY ("MoveId2") REFERENCES "Moves" ("Id"),
    CONSTRAINT "FK_PokemonInstances_Moves_MoveId3" FOREIGN KEY ("MoveId3") REFERENCES "Moves" ("Id"),
    CONSTRAINT "FK_PokemonInstances_Natures_NatureId" FOREIGN KEY ("NatureId") REFERENCES "Natures" ("Id"),
    CONSTRAINT "FK_PokemonInstances_Pokemon_PokemonId" FOREIGN KEY ("PokemonId") REFERENCES "Pokemon" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PokemonInstances_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BoxSlots" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BoxId" integer NOT NULL,
    "PokemonInstanceId" integer NOT NULL,
    "SlotNumber" integer NOT NULL,
    CONSTRAINT "PK_BoxSlots" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BoxSlots_Boxes_BoxId" FOREIGN KEY ("BoxId") REFERENCES "Boxes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BoxSlots_PokemonInstances_PokemonInstanceId" FOREIGN KEY ("PokemonInstanceId") REFERENCES "PokemonInstances" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TeamMembers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TeamId" integer NOT NULL,
    "PokemonInstanceId" integer NOT NULL,
    CONSTRAINT "PK_TeamMembers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TeamMembers_PokemonInstances_PokemonInstanceId" FOREIGN KEY ("PokemonInstanceId") REFERENCES "PokemonInstances" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TeamMembers_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Boxes_GameId" ON "Boxes" ("GameId");

CREATE INDEX "IX_Boxes_UserId" ON "Boxes" ("UserId");

CREATE INDEX "IX_BoxSlots_BoxId" ON "BoxSlots" ("BoxId");

CREATE INDEX "IX_BoxSlots_PokemonInstanceId" ON "BoxSlots" ("PokemonInstanceId");

CREATE INDEX "IX_Forms_PokemonId" ON "Forms" ("PokemonId");

CREATE INDEX "IX_Forms_Type1Id" ON "Forms" ("Type1Id");

CREATE INDEX "IX_Forms_Type2Id" ON "Forms" ("Type2Id");

CREATE INDEX "IX_MoveLearning_GameId" ON "MoveLearning" ("GameId");

CREATE INDEX "IX_MoveLearning_MethodId" ON "MoveLearning" ("MethodId");

CREATE INDEX "IX_MoveLearning_MoveId" ON "MoveLearning" ("MoveId");

CREATE INDEX "IX_MoveLearning_PokemonId" ON "MoveLearning" ("PokemonId");

CREATE INDEX "IX_Moves_CategoryId" ON "Moves" ("CategoryId");

CREATE INDEX "IX_Moves_TypeId" ON "Moves" ("TypeId");

CREATE INDEX "IX_Natures_DecreasedStatId" ON "Natures" ("DecreasedStatId");

CREATE INDEX "IX_Natures_IncreasedStatId" ON "Natures" ("IncreasedStatId");

CREATE INDEX "IX_Natures_StatId" ON "Natures" ("StatId");

CREATE INDEX "IX_Natures_StatId1" ON "Natures" ("StatId1");

CREATE INDEX "IX_Pokemon_GameId" ON "Pokemon" ("GameId");

CREATE INDEX "IX_Pokemon_Type1Id" ON "Pokemon" ("Type1Id");

CREATE INDEX "IX_Pokemon_Type2Id" ON "Pokemon" ("Type2Id");

CREATE INDEX "IX_PokemonAbilities_AbilityId" ON "PokemonAbilities" ("AbilityId");

CREATE INDEX "IX_PokemonAbilities_PokemonId" ON "PokemonAbilities" ("PokemonId");

CREATE INDEX "IX_PokemonInstances_AbilityId" ON "PokemonInstances" ("AbilityId");

CREATE INDEX "IX_PokemonInstances_FormId" ON "PokemonInstances" ("FormId");

CREATE INDEX "IX_PokemonInstances_GameId" ON "PokemonInstances" ("GameId");

CREATE INDEX "IX_PokemonInstances_HeldItemId" ON "PokemonInstances" ("HeldItemId");

CREATE INDEX "IX_PokemonInstances_Move1Id" ON "PokemonInstances" ("Move1Id");

CREATE INDEX "IX_PokemonInstances_Move2Id" ON "PokemonInstances" ("Move2Id");

CREATE INDEX "IX_PokemonInstances_Move3Id" ON "PokemonInstances" ("Move3Id");

CREATE INDEX "IX_PokemonInstances_Move4Id" ON "PokemonInstances" ("Move4Id");

CREATE INDEX "IX_PokemonInstances_MoveId" ON "PokemonInstances" ("MoveId");

CREATE INDEX "IX_PokemonInstances_MoveId1" ON "PokemonInstances" ("MoveId1");

CREATE INDEX "IX_PokemonInstances_MoveId2" ON "PokemonInstances" ("MoveId2");

CREATE INDEX "IX_PokemonInstances_MoveId3" ON "PokemonInstances" ("MoveId3");

CREATE INDEX "IX_PokemonInstances_NatureId" ON "PokemonInstances" ("NatureId");

CREATE INDEX "IX_PokemonInstances_PokemonId" ON "PokemonInstances" ("PokemonId");

CREATE INDEX "IX_PokemonInstances_UserId" ON "PokemonInstances" ("UserId");

CREATE INDEX "IX_TeamMembers_PokemonInstanceId" ON "TeamMembers" ("PokemonInstanceId");

CREATE INDEX "IX_TeamMembers_TeamId" ON "TeamMembers" ("TeamId");

CREATE INDEX "IX_Teams_GameId" ON "Teams" ("GameId");

CREATE INDEX "IX_Teams_UserId" ON "Teams" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250417080158_InitialCreate', '9.0.4');

ALTER TABLE "Users" ADD "Auth0Id" text NOT NULL DEFAULT '';

ALTER TABLE "Teams" ALTER COLUMN "Description" DROP NOT NULL;

ALTER TABLE "PokemonInstances" ALTER COLUMN "Ribbons" DROP NOT NULL;

ALTER TABLE "PokemonInstances" ALTER COLUMN "OriginalTrainerName" DROP NOT NULL;

ALTER TABLE "PokemonInstances" ALTER COLUMN "OriginalTrainerId" DROP NOT NULL;

ALTER TABLE "PokemonInstances" ALTER COLUMN "Nickname" DROP NOT NULL;

ALTER TABLE "PokemonInstances" ALTER COLUMN "MetLocation" DROP NOT NULL;

ALTER TABLE "Pokemon" ALTER COLUMN "FormName" DROP NOT NULL;

ALTER TABLE "Moves" ALTER COLUMN "Effect" DROP NOT NULL;

ALTER TABLE "MoveLearning" ALTER COLUMN "TMNumber" DROP NOT NULL;

ALTER TABLE "Games" ALTER COLUMN "Region" DROP NOT NULL;

ALTER TABLE "Boxes" ALTER COLUMN "Name" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250418150732_AddAuth0Id', '9.0.4');

CREATE TABLE "MoveGame" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MoveId" integer NOT NULL,
    "GameId" integer NOT NULL,
    "MoveGameId" integer NOT NULL,
    CONSTRAINT "PK_MoveGame" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MoveGame_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MoveGame_Moves_MoveId" FOREIGN KEY ("MoveId") REFERENCES "Moves" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_MoveGame_GameId" ON "MoveGame" ("GameId");

CREATE INDEX "IX_MoveGame_MoveId" ON "MoveGame" ("MoveId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250421192716_MoveGame', '9.0.4');

ALTER TABLE "MoveLearning" DROP CONSTRAINT "FK_MoveLearning_Games_GameId";

ALTER TABLE "MoveLearning" DROP CONSTRAINT "FK_MoveLearning_Moves_MoveId";

DROP INDEX "IX_MoveLearning_GameId";

ALTER TABLE "MoveLearning" DROP COLUMN "GameId";

ALTER TABLE "MoveLearning" RENAME COLUMN "MoveId" TO "MoveGameId";

ALTER INDEX "IX_MoveLearning_MoveId" RENAME TO "IX_MoveLearning_MoveGameId";

ALTER TABLE "MoveLearning" ADD CONSTRAINT "FK_MoveLearning_MoveGame_MoveGameId" FOREIGN KEY ("MoveGameId") REFERENCES "MoveGame" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250422093137_MoveGame-MoveLearning', '9.0.4');

ALTER TABLE "Users" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Users" ADD "UpdatedAt" timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250422130317_pending', '9.0.4');

CREATE TABLE "TypeGame" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TypeId" integer NOT NULL,
    "GameId" integer NOT NULL,
    CONSTRAINT "PK_TypeGame" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TypeGame_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TypeGame_Types_TypeId" FOREIGN KEY ("TypeId") REFERENCES "Types" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TypeGame_GameId" ON "TypeGame" ("GameId");

CREATE INDEX "IX_TypeGame_TypeId" ON "TypeGame" ("TypeId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250422134013_TypeGame', '9.0.4');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250423060517_package-renaming', '9.0.4');

ALTER TABLE "PokemonInstances" ADD "EVSpecial" integer;

ALTER TABLE "PokemonInstances" ADD "IVSpecial" integer;

ALTER TABLE "Pokemon" ALTER COLUMN "SpDefense" DROP NOT NULL;

ALTER TABLE "Pokemon" ALTER COLUMN "SpAttack" DROP NOT NULL;

ALTER TABLE "Pokemon" ADD "Special" integer;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250423133613_AddedSpecialStatForGen1', '9.0.4');

ALTER TABLE "MoveGame" DROP CONSTRAINT "FK_MoveGame_Games_GameId";

ALTER TABLE "MoveGame" DROP CONSTRAINT "FK_MoveGame_Moves_MoveId";

ALTER TABLE "MoveLearning" DROP CONSTRAINT "FK_MoveLearning_MoveGame_MoveGameId";

ALTER TABLE "MoveGame" DROP CONSTRAINT "PK_MoveGame";

ALTER TABLE "MoveGame" RENAME TO "MoveGames";

ALTER INDEX "IX_MoveGame_MoveId" RENAME TO "IX_MoveGames_MoveId";

ALTER INDEX "IX_MoveGame_GameId" RENAME TO "IX_MoveGames_GameId";

ALTER TABLE "MoveGames" ADD CONSTRAINT "PK_MoveGames" PRIMARY KEY ("Id");

ALTER TABLE "MoveGames" ADD CONSTRAINT "FK_MoveGames_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("Id") ON DELETE CASCADE;

ALTER TABLE "MoveGames" ADD CONSTRAINT "FK_MoveGames_Moves_MoveId" FOREIGN KEY ("MoveId") REFERENCES "Moves" ("Id") ON DELETE CASCADE;

ALTER TABLE "MoveLearning" ADD CONSTRAINT "FK_MoveLearning_MoveGames_MoveGameId" FOREIGN KEY ("MoveGameId") REFERENCES "MoveGames" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250423183048_MoveGame-Table', '9.0.4');

ALTER TABLE "TypeGame" DROP CONSTRAINT "FK_TypeGame_Games_GameId";

ALTER TABLE "TypeGame" DROP CONSTRAINT "FK_TypeGame_Types_TypeId";

ALTER TABLE "TypeGame" DROP CONSTRAINT "PK_TypeGame";

ALTER TABLE "Moves" DROP COLUMN "Name";

ALTER TABLE "TypeGame" RENAME TO "TypeGames";

ALTER INDEX "IX_TypeGame_TypeId" RENAME TO "IX_TypeGames_TypeId";

ALTER INDEX "IX_TypeGame_GameId" RENAME TO "IX_TypeGames_GameId";

ALTER TABLE "Moves" ADD "NameId" integer NOT NULL DEFAULT 0;

ALTER TABLE "TypeGames" ADD "GameTypeId" integer NOT NULL DEFAULT 0;

ALTER TABLE "TypeGames" ADD CONSTRAINT "PK_TypeGames" PRIMARY KEY ("Id");

CREATE TABLE "MoveNames" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_MoveNames" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Moves_NameId" ON "Moves" ("NameId");

ALTER TABLE "Moves" ADD CONSTRAINT "FK_Moves_MoveNames_NameId" FOREIGN KEY ("NameId") REFERENCES "MoveNames" ("Id") ON DELETE CASCADE;

ALTER TABLE "TypeGames" ADD CONSTRAINT "FK_TypeGames_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("Id") ON DELETE CASCADE;

ALTER TABLE "TypeGames" ADD CONSTRAINT "FK_TypeGames_Types_TypeId" FOREIGN KEY ("TypeId") REFERENCES "Types" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250424174523_MoveName', '9.0.4');

ALTER TABLE "Abilities" DROP COLUMN "Name";

ALTER TABLE "Abilities" ADD "NameId" integer NOT NULL DEFAULT 0;

CREATE TABLE "AbilityGames" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AbilityId" integer NOT NULL,
    "GameId" integer NOT NULL,
    "AbilityGameId" integer NOT NULL,
    CONSTRAINT "PK_AbilityGames" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AbilityGames_Abilities_AbilityId" FOREIGN KEY ("AbilityId") REFERENCES "Abilities" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AbilityGames_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AbilityNames" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_AbilityNames" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Abilities_NameId" ON "Abilities" ("NameId");

CREATE INDEX "IX_AbilityGames_AbilityId" ON "AbilityGames" ("AbilityId");

CREATE INDEX "IX_AbilityGames_GameId" ON "AbilityGames" ("GameId");

ALTER TABLE "Abilities" ADD CONSTRAINT "FK_Abilities_AbilityNames_NameId" FOREIGN KEY ("NameId") REFERENCES "AbilityNames" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250425092329_AbilityTables', '9.0.4');

ALTER TABLE "MoveLearning" DROP CONSTRAINT "FK_MoveLearning_MoveGames_MoveGameId";

DROP TABLE "AbilityGames";

ALTER TABLE "TypeGames" RENAME COLUMN "GameTypeId" TO "TypeInGameId";

ALTER TABLE "MoveLearning" RENAME COLUMN "MoveGameId" TO "GameInMoveId";

ALTER INDEX "IX_MoveLearning_MoveGameId" RENAME TO "IX_MoveLearning_GameInMoveId";

ALTER TABLE "MoveGames" RENAME COLUMN "MoveGameId" TO "MoveInGameId";

CREATE TABLE "GameAbilities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AbilityId" integer NOT NULL,
    "GameId" integer NOT NULL,
    "AbilityInGameId" integer NOT NULL,
    CONSTRAINT "PK_GameAbilities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GameAbilities_Abilities_AbilityId" FOREIGN KEY ("AbilityId") REFERENCES "Abilities" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GameAbilities_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_GameAbilities_AbilityId" ON "GameAbilities" ("AbilityId");

CREATE INDEX "IX_GameAbilities_GameId" ON "GameAbilities" ("GameId");

ALTER TABLE "MoveLearning" ADD CONSTRAINT "FK_MoveLearning_MoveGames_GameInMoveId" FOREIGN KEY ("GameInMoveId") REFERENCES "MoveGames" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250425111608_Refactor-GameTables', '9.0.4');

ALTER TABLE "MoveGames" DROP CONSTRAINT "FK_MoveGames_Games_GameId";

ALTER TABLE "MoveGames" DROP CONSTRAINT "FK_MoveGames_Moves_MoveId";

ALTER TABLE "MoveLearning" DROP CONSTRAINT "FK_MoveLearning_MoveGames_GameInMoveId";

ALTER TABLE "TypeGames" DROP CONSTRAINT "FK_TypeGames_Games_GameId";

ALTER TABLE "TypeGames" DROP CONSTRAINT "FK_TypeGames_Types_TypeId";

ALTER TABLE "TypeGames" DROP CONSTRAINT "PK_TypeGames";

ALTER TABLE "MoveGames" DROP CONSTRAINT "PK_MoveGames";

ALTER TABLE "TypeGames" RENAME TO "GameTypes";

ALTER TABLE "MoveGames" RENAME TO "GameMoves";

ALTER INDEX "IX_TypeGames_TypeId" RENAME TO "IX_GameTypes_TypeId";

ALTER INDEX "IX_TypeGames_GameId" RENAME TO "IX_GameTypes_GameId";

ALTER INDEX "IX_MoveGames_MoveId" RENAME TO "IX_GameMoves_MoveId";

ALTER INDEX "IX_MoveGames_GameId" RENAME TO "IX_GameMoves_GameId";

ALTER TABLE "GameTypes" ADD CONSTRAINT "PK_GameTypes" PRIMARY KEY ("Id");

ALTER TABLE "GameMoves" ADD CONSTRAINT "PK_GameMoves" PRIMARY KEY ("Id");

ALTER TABLE "GameMoves" ADD CONSTRAINT "FK_GameMoves_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("Id") ON DELETE CASCADE;

ALTER TABLE "GameMoves" ADD CONSTRAINT "FK_GameMoves_Moves_MoveId" FOREIGN KEY ("MoveId") REFERENCES "Moves" ("Id") ON DELETE CASCADE;

ALTER TABLE "GameTypes" ADD CONSTRAINT "FK_GameTypes_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("Id") ON DELETE CASCADE;

ALTER TABLE "GameTypes" ADD CONSTRAINT "FK_GameTypes_Types_TypeId" FOREIGN KEY ("TypeId") REFERENCES "Types" ("Id") ON DELETE CASCADE;

ALTER TABLE "MoveLearning" ADD CONSTRAINT "FK_MoveLearning_GameMoves_GameInMoveId" FOREIGN KEY ("GameInMoveId") REFERENCES "GameMoves" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250425171653_Rename-dGameTables', '9.0.4');

ALTER TABLE "PokemonInstances" DROP CONSTRAINT "FK_PokemonInstances_Forms_FormId";

DROP TABLE "Forms";

DROP TABLE "MoveLearning";

CREATE TABLE "PokemonForms" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PokemonId" integer NOT NULL,
    "Name" text NOT NULL,
    "IsRegional" boolean NOT NULL,
    "IsMega" boolean NOT NULL,
    "IsGigantamax" boolean NOT NULL,
    "FormOrder" integer,
    "Type1Id" integer NOT NULL,
    "Type2Id" integer,
    CONSTRAINT "PK_PokemonForms" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PokemonForms_Pokemon_PokemonId" FOREIGN KEY ("PokemonId") REFERENCES "Pokemon" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PokemonForms_Types_Type1Id" FOREIGN KEY ("Type1Id") REFERENCES "Types" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PokemonForms_Types_Type2Id" FOREIGN KEY ("Type2Id") REFERENCES "Types" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "PokemonMove" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PokemonId" integer NOT NULL,
    "GameInMoveId" integer NOT NULL,
    "MethodId" integer NOT NULL,
    "Level" integer,
    "TMNumber" text,
    "IsTutor" boolean NOT NULL,
    "IsEggMove" boolean NOT NULL,
    CONSTRAINT "PK_PokemonMove" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PokemonMove_GameMoves_GameInMoveId" FOREIGN KEY ("GameInMoveId") REFERENCES "GameMoves" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PokemonMove_MoveLearningMethods_MethodId" FOREIGN KEY ("MethodId") REFERENCES "MoveLearningMethods" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PokemonMove_Pokemon_PokemonId" FOREIGN KEY ("PokemonId") REFERENCES "Pokemon" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_PokemonForms_PokemonId" ON "PokemonForms" ("PokemonId");

CREATE INDEX "IX_PokemonForms_Type1Id" ON "PokemonForms" ("Type1Id");

CREATE INDEX "IX_PokemonForms_Type2Id" ON "PokemonForms" ("Type2Id");

CREATE INDEX "IX_PokemonMove_GameInMoveId" ON "PokemonMove" ("GameInMoveId");

CREATE INDEX "IX_PokemonMove_MethodId" ON "PokemonMove" ("MethodId");

CREATE INDEX "IX_PokemonMove_PokemonId" ON "PokemonMove" ("PokemonId");

ALTER TABLE "PokemonInstances" ADD CONSTRAINT "FK_PokemonInstances_PokemonForms_FormId" FOREIGN KEY ("FormId") REFERENCES "PokemonForms" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250428081642_Renamed-Pokemon-Related-Tables', '9.0.4');

ALTER TABLE "PokemonInstances" DROP CONSTRAINT "FK_PokemonInstances_Users_UserId";

DROP TABLE "BoxSlots";

DROP TABLE "TeamMembers";

DROP TABLE "Boxes";

DROP TABLE "Teams";

ALTER TABLE "PokemonInstances" RENAME COLUMN "UserId" TO "SaveId";

ALTER INDEX "IX_PokemonInstances_UserId" RENAME TO "IX_PokemonInstances_SaveId";

CREATE TABLE "Saves" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "GameId" integer NOT NULL,
    CONSTRAINT "PK_Saves" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Saves_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Saves_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SaveBoxes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SaveId" integer NOT NULL,
    "Name" text,
    CONSTRAINT "PK_SaveBoxes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SaveBoxes_Saves_SaveId" FOREIGN KEY ("SaveId") REFERENCES "Saves" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SaveTeams" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SaveId" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SaveTeams" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SaveTeams_Saves_SaveId" FOREIGN KEY ("SaveId") REFERENCES "Saves" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SaveBoxSlots" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BoxId" integer NOT NULL,
    "PokemonInstanceId" integer NOT NULL,
    "SlotNumber" integer NOT NULL,
    CONSTRAINT "PK_SaveBoxSlots" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SaveBoxSlots_PokemonInstances_PokemonInstanceId" FOREIGN KEY ("PokemonInstanceId") REFERENCES "PokemonInstances" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SaveBoxSlots_SaveBoxes_BoxId" FOREIGN KEY ("BoxId") REFERENCES "SaveBoxes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SaveTeamMembers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TeamId" integer NOT NULL,
    "PokemonInstanceId" integer NOT NULL,
    CONSTRAINT "PK_SaveTeamMembers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SaveTeamMembers_PokemonInstances_PokemonInstanceId" FOREIGN KEY ("PokemonInstanceId") REFERENCES "PokemonInstances" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SaveTeamMembers_SaveTeams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "SaveTeams" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_SaveBoxes_SaveId" ON "SaveBoxes" ("SaveId");

CREATE INDEX "IX_SaveBoxSlots_BoxId" ON "SaveBoxSlots" ("BoxId");

CREATE INDEX "IX_SaveBoxSlots_PokemonInstanceId" ON "SaveBoxSlots" ("PokemonInstanceId");

CREATE INDEX "IX_Saves_GameId" ON "Saves" ("GameId");

CREATE INDEX "IX_Saves_UserId" ON "Saves" ("UserId");

CREATE INDEX "IX_SaveTeamMembers_PokemonInstanceId" ON "SaveTeamMembers" ("PokemonInstanceId");

CREATE INDEX "IX_SaveTeamMembers_TeamId" ON "SaveTeamMembers" ("TeamId");

CREATE INDEX "IX_SaveTeams_SaveId" ON "SaveTeams" ("SaveId");

ALTER TABLE "PokemonInstances" ADD CONSTRAINT "FK_PokemonInstances_Saves_SaveId" FOREIGN KEY ("SaveId") REFERENCES "Saves" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250428121422_Saves', '9.0.4');

ALTER TABLE "Saves" ADD "TeamId" integer NOT NULL DEFAULT 0;

CREATE INDEX "IX_Saves_TeamId" ON "Saves" ("TeamId");

ALTER TABLE "Saves" ADD CONSTRAINT "FK_Saves_SaveTeams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "SaveTeams" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250428212240_Fix-SavesBox-Relation', '9.0.4');

CREATE UNIQUE INDEX "IX_Users_Auth0Id" ON "Users" ("Auth0Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250428214106_Fix-Saves-UserId-Index', '9.0.4');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250428214323_User-NavProperties', '9.0.4');

ALTER TABLE "Pokemon" DROP CONSTRAINT "FK_Pokemon_Types_Type1Id";

ALTER TABLE "Pokemon" DROP CONSTRAINT "FK_Pokemon_Types_Type2Id";

ALTER TABLE "PokemonInstances" DROP CONSTRAINT "FK_PokemonInstances_Games_GameId";

ALTER TABLE "PokemonInstances" DROP CONSTRAINT "FK_PokemonInstances_PokemonForms_FormId";

DROP INDEX "IX_PokemonInstances_GameId";

DROP INDEX "IX_Pokemon_Type1Id";

DROP INDEX "IX_Pokemon_Type2Id";

ALTER TABLE "PokemonInstances" DROP COLUMN "GameId";

ALTER TABLE "PokemonInstances" DROP COLUMN "MetLevel";

ALTER TABLE "PokemonInstances" DROP COLUMN "MetLocation";

ALTER TABLE "PokemonInstances" DROP COLUMN "OriginalTrainerId";

ALTER TABLE "PokemonInstances" DROP COLUMN "OriginalTrainerName";

ALTER TABLE "PokemonInstances" DROP COLUMN "Ribbons";

ALTER TABLE "Pokemon" DROP COLUMN "Attack";

ALTER TABLE "Pokemon" DROP COLUMN "Defense";

ALTER TABLE "Pokemon" DROP COLUMN "FormName";

ALTER TABLE "Pokemon" DROP COLUMN "HP";

ALTER TABLE "Pokemon" DROP COLUMN "IsGigantamax";

ALTER TABLE "Pokemon" DROP COLUMN "IsMega";

ALTER TABLE "Pokemon" DROP COLUMN "IsRegionalForm";

ALTER TABLE "Pokemon" DROP COLUMN "SpAttack";

ALTER TABLE "Pokemon" DROP COLUMN "SpDefense";

ALTER TABLE "Pokemon" DROP COLUMN "Special";

ALTER TABLE "Pokemon" DROP COLUMN "Speed";

ALTER TABLE "Pokemon" DROP COLUMN "Type1Id";

ALTER TABLE "Pokemon" DROP COLUMN "Type2Id";

ALTER TABLE "PokemonForms" RENAME COLUMN "FormOrder" TO "Special";

UPDATE "PokemonInstances" SET "FormId" = 0 WHERE "FormId" IS NULL;
ALTER TABLE "PokemonInstances" ALTER COLUMN "FormId" SET NOT NULL;
ALTER TABLE "PokemonInstances" ALTER COLUMN "FormId" SET DEFAULT 0;

ALTER TABLE "PokemonForms" ADD "Attack" integer NOT NULL DEFAULT 0;

ALTER TABLE "PokemonForms" ADD "Defense" integer NOT NULL DEFAULT 0;

ALTER TABLE "PokemonForms" ADD "HP" integer NOT NULL DEFAULT 0;

ALTER TABLE "PokemonForms" ADD "InternalId" integer;

ALTER TABLE "PokemonForms" ADD "IsDefault" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "PokemonForms" ADD "SpAttack" integer;

ALTER TABLE "PokemonForms" ADD "SpDefense" integer;

ALTER TABLE "PokemonForms" ADD "Speed" integer NOT NULL DEFAULT 0;

ALTER TABLE "PokemonInstances" ADD CONSTRAINT "FK_PokemonInstances_PokemonForms_FormId" FOREIGN KEY ("FormId") REFERENCES "PokemonForms" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250503173337_ChangedPokemonFormRelations', '9.0.4');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250512213159_AutoincrementOnKeys', '9.0.4');

ALTER TABLE "Natures" DROP CONSTRAINT "FK_Natures_Stats_StatId";

ALTER TABLE "Natures" DROP CONSTRAINT "FK_Natures_Stats_StatId1";

DROP INDEX "IX_Natures_StatId";

DROP INDEX "IX_Natures_StatId1";

ALTER TABLE "Natures" DROP COLUMN "StatId";

ALTER TABLE "Natures" DROP COLUMN "StatId1";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250514162802_FixNatureStatRelation', '9.0.4');

ALTER TABLE "Saves" DROP CONSTRAINT "FK_Saves_SaveTeams_TeamId";

ALTER TABLE "SaveTeamMembers" DROP CONSTRAINT "FK_SaveTeamMembers_SaveTeams_TeamId";

DROP INDEX "IX_SaveTeams_SaveId";

DROP INDEX "IX_Saves_TeamId";

ALTER TABLE "SaveTeams" DROP COLUMN "CreatedAt";

ALTER TABLE "SaveTeams" DROP COLUMN "Description";

ALTER TABLE "SaveTeams" DROP COLUMN "Name";

ALTER TABLE "Saves" DROP COLUMN "TeamId";

ALTER TABLE "SaveTeamMembers" RENAME COLUMN "TeamId" TO "PartyId";

ALTER INDEX "IX_SaveTeamMembers_TeamId" RENAME TO "IX_SaveTeamMembers_PartyId";

ALTER TABLE "Saves" ADD "Name" text NOT NULL DEFAULT '';

CREATE UNIQUE INDEX "IX_SaveTeams_SaveId" ON "SaveTeams" ("SaveId");

ALTER TABLE "SaveTeamMembers" ADD CONSTRAINT "FK_SaveTeamMembers_SaveTeams_PartyId" FOREIGN KEY ("PartyId") REFERENCES "SaveTeams" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250518173354_FixSaveTeamCircularDependecy', '9.0.4');

ALTER TABLE "Saves" DROP CONSTRAINT "FK_Saves_Users_UserId";

DROP INDEX "IX_Saves_UserId";

ALTER TABLE "Saves" ALTER COLUMN "UserId" TYPE text;

ALTER TABLE "Saves" ADD "LastUpdatedTime" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Saves" ADD "UserId1" integer;

CREATE INDEX "IX_Saves_UserId1" ON "Saves" ("UserId1");

ALTER TABLE "Saves" ADD CONSTRAINT "FK_Saves_Users_UserId1" FOREIGN KEY ("UserId1") REFERENCES "Users" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250520091751_SaveIdAsString', '9.0.4');

ALTER TABLE "Saves" DROP CONSTRAINT "FK_Saves_Users_UserId1";

DROP INDEX "IX_Saves_UserId1";

ALTER TABLE "Saves" DROP COLUMN "UserId1";

ALTER TABLE "Saves" ALTER COLUMN "UserId" TYPE integer USING "UserId"::integer;

CREATE INDEX "IX_Saves_UserId" ON "Saves" ("UserId");

ALTER TABLE "Saves" ADD CONSTRAINT "FK_Saves_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250520120342_RevertSaveUserIdAsInt', '9.0.4');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250520134624_CascadeDeleteForSaveRelations', '9.0.4');

ALTER TABLE "Saves" RENAME COLUMN "LastUpdatedTime" TO "UpdatedAt";

ALTER TABLE "Saves" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250520163635_SaveTimeFields', '9.0.4');

ALTER TABLE "Saves" ADD "Badges" smallint NOT NULL DEFAULT 0;

ALTER TABLE "Saves" ADD "Description" text;

ALTER TABLE "Saves" ADD "IsFavorite" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Saves" ADD "PlayTime" text;

ALTER TABLE "Saves" ADD "PlayerName" text;

ALTER TABLE "Saves" ADD "Tags" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250614141953_MoreSaveFileProperties', '9.0.4');

ALTER TABLE "Saves" ADD "PokemonCaught" integer NOT NULL DEFAULT 0;

ALTER TABLE "Saves" ADD "PokemonSeen" integer NOT NULL DEFAULT 0;

ALTER TABLE "SaveBoxes" ADD "Capacity" integer NOT NULL DEFAULT 0;

ALTER TABLE "SaveBoxes" ADD "Count" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250615100404_MoreSaveProperties', '9.0.4');

ALTER TABLE "Saves" ADD "PokemonTotal" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250626201518_saveTotalPokmeonCount', '9.0.4');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250706202512_PathForRom', '9.0.4');

ALTER TABLE "Games" ADD "Path" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250706210029_FixPath', '9.0.4');

ALTER TABLE "Saves" ADD "Path" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250708201617_SavePath', '9.0.4');

COMMIT;

